name: Run pattern tests

on:
  # Triggers on push/pull only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows running workflow manually
  workflow_dispatch:

jobs:
  # single job
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run prepared test cases against current versioned pattern
        run: perl test.pl
